import { InputGeneric } from "src/app/shared/components/inputs-generic/model/inputGeneric";

export const inputGenericData: InputGeneric[] = [
    { label: "",
      class: "w-100 ",
      appearance: null,
      type: "hidden",
      typeInput:"normal",
      formControlName:"id",
      data : null },

    { label: "Title",
      class: "col-md-8 col-sm-8",
      appearance: "outline",
      type: "text",
      typeInput:"matInput",
      formControlName: "title",
      maxLength: 150,
      data : null,
      required: false },

    { label: "Page Count",
      class: "col-md-4 col-sm-4",
      appearance: "outline",
      type: "text",
      typeInput:"matInput",
      formControlName: "pageCount",
      data : null,
      required: false },

    { label: "Description",
      class: "col-md-12 col-sm-12",
      appearance: "outline",
      type: "textarea",
      maxLength: 500,
      typeInput:"matInput",
      formControlName: "description",
      rows: 2,
      data : null, },

    { label: "Excerpt",
      class: "col-md-12 col-sm-12",
      appearance: "outline",
      type: "textarea",
      maxLength: 1000,
      typeInput:"matInput",
      formControlName: "excerpt",
      rows: 5,
      data : null, },

    { label: "Publish Date",
      class: "col-md-12 col-sm-12",
      appearance: "outline",
      type: "date",
      typeInput:"matInput",
      formControlName: "publishDate",
      data : null, },

];
